server:
  port: 8081

spring:
  datasource:
    username: wfpan
    password: 123456
    #url中database为对应的数据库名称
    url: jdbc:mysql://47.103.214.177:3306/software?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/software?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.cgd.demo.entity

#showSql
logging:
  level:
    com.cgd.demo.mapper: debug

